# Generated by Django 3.1 on 2020-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('contactname', models.CharField(max_length=50)),
                ('contactEmail', models.CharField(default='', max_length=70)),
                ('contactnum', models.CharField(default='', max_length=70)),
                ('contactquery', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
