# Generated by Django 3.1 on 2020-08-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contactEmail',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactnum',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactquery',
            new_name='num',
        ),
    ]
